# Generated by Django 4.2.7 on 2025-09-27 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('type_personnel', models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('AGENT_SECURITE', 'Agent de sécurité'), ('AGENT_ADMINISTRATIF', 'Agent administratif'), ('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('PSYCHOLOGUE', 'Psychologue'), ('CUISINIER', 'Cuisinier'), ('NETTOYEUR', 'Agent de nettoyage'), ('GARDIEN', 'Gardien')], max_length=30, verbose_name='Type de personnel')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('RETRAITE', 'Retraité')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('date_fin_contrat', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('specialite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Spécialité')),
                ('numero_ordre', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'ordre (pour médecins)")),
                ('heures_travail_semaine', models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='Heures de travail par semaine')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom du contact d'urgence")),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone du contact d'urgence")),
                ('contact_urgence_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name="Relation avec le contact d'urgence")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SanctionPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(max_length=100, verbose_name='Type de sanction')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_sanction', models.DateField(verbose_name='Date de sanction')),
                ('duree_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée en jours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='personnel.personnel', verbose_name='Personnel')),
                ('sanctionne_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_appliquees', to=settings.AUTH_USER_MODEL, verbose_name='Sanctionné par')),
            ],
            options={
                'verbose_name': 'Sanction personnel',
                'verbose_name_plural': 'Sanctions personnel',
                'ordering': ['-date_sanction'],
            },
        ),
        migrations.CreateModel(
            name='FormationPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=200, verbose_name='Nom de la formation')),
                ('organisme', models.CharField(max_length=200, verbose_name='Organisme formateur')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('duree_heures', models.PositiveIntegerField(verbose_name='Durée en heures')),
                ('certificat', models.FileField(blank=True, null=True, upload_to='certificats/', verbose_name='Certificat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='personnel.personnel', verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Formation personnel',
                'verbose_name_plural': 'Formations personnel',
                'ordering': ['-date_fin'],
            },
        ),
    ]
