# Generated by Django 4.2.7 on 2026-02-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detenus', '0003_centrepenitencier_adminprison_detenu_centre'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detenus.centrepenitencier', verbose_name='Centre pénitencier'),
        ),
    ]
