# Generated by Django 4.2.7 on 2026-02-19 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0002_personnel_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
