# Generated by Django 4.2.7 on 2025-09-27 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('type_rapport', models.CharField(choices=[('STATISTIQUES', 'Statistiques'), ('DETENUS', 'Détenus'), ('PERSONNEL', 'Personnel'), ('VISITES', 'Visites'), ('SOINS', 'Soins médicaux'), ('LOGISTIQUE', 'Logistique'), ('SECURITE', 'Sécurité'), ('FINANCIER', 'Financier')], max_length=20, verbose_name='Type de rapport')),
                ('description', models.TextField(verbose_name='Description')),
                ('template', models.TextField(verbose_name='Template')),
                ('parametres_defaut', models.JSONField(blank=True, null=True, verbose_name='Paramètres par défaut')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapports',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TableauBord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du tableau de bord')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('configuration', models.JSONField(verbose_name='Configuration')),
                ('est_public', models.BooleanField(default=False, verbose_name='Est public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('type_rapport', models.CharField(choices=[('STATISTIQUES', 'Statistiques'), ('DETENUS', 'Détenus'), ('PERSONNEL', 'Personnel'), ('VISITES', 'Visites'), ('SOINS', 'Soins médicaux'), ('LOGISTIQUE', 'Logistique'), ('SECURITE', 'Sécurité'), ('FINANCIER', 'Financier')], max_length=20, verbose_name='Type de rapport')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('parametres', models.JSONField(blank=True, null=True, verbose_name='Paramètres')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
