# Generated by Django 4.2.7 on 2026-01-25 00:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detenus', '0003_centrepenitencier_adminprison_detenu_centre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la caméra')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code de la caméra')),
                ('type_camera', models.CharField(choices=[('INTERIEURE', 'Intérieure'), ('EXTERIEURE', 'Extérieure'), ('PTZ', 'PTZ (Pan-Tilt-Zoom)'), ('DOME', 'Dôme'), ('BULLET', 'Bullet'), ('FISHEYE', 'Fisheye')], default='INTERIEURE', max_length=20, verbose_name='Type de caméra')),
                ('emplacement', models.CharField(max_length=200, verbose_name='Emplacement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Port')),
                ('url_flux', models.URLField(blank=True, null=True, verbose_name='URL du flux vidéo')),
                ('resolution', models.CharField(default='1920x1080', max_length=20, verbose_name='Résolution')),
                ('fps', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Images par seconde')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='INACTIVE', max_length=20, verbose_name='Statut')),
                ('detection_active', models.BooleanField(default=True, verbose_name='Détection active')),
                ('reconnaissance_faciale_active', models.BooleanField(default=True, verbose_name='Reconnaissance faciale active')),
                ('qualite_detection', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('BONNE', 'Bonne'), ('EXCELLENTE', 'Excellente')], default='MOYENNE', max_length=20, verbose_name='Qualité de détection')),
                ('angle_vue', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Angle de vue (degrés)')),
                ('portee_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Portée maximale (mètres)')),
                ('date_installation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'installation")),
                ('derniere_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detenus.centrepenitencier', verbose_name='Centre pénitencier')),
            ],
            options={
                'verbose_name': 'Caméra',
                'verbose_name_plural': 'Caméras',
                'ordering': ['centre__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('coordonnees', models.JSONField(help_text='Coordonnées polygonales de la zone [x1,y1, x2,y2, ...]', verbose_name='Coordonnées de la zone')),
                ('type_zone', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('COULOIR', 'Couloir'), ('COUR', 'Cour'), ('CELLULE', 'Cellule'), ('REFECTOIRE', 'Réfectoire'), ('ATELIER', 'Atelier'), ('INFIRMERIE', 'Infirmerie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Type de zone')),
                ('detection_active', models.BooleanField(default=True, verbose_name='Détection active')),
                ('seuil_alerte', models.PositiveIntegerField(default=1, help_text='Nombre de détections avant alerte', verbose_name="Seuil d'alerte")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='surveillance.camera', verbose_name='Caméra')),
            ],
            options={
                'verbose_name': 'Zone de surveillance',
                'verbose_name_plural': 'Zones de surveillance',
                'ordering': ['camera__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilFacialDetenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encodage_facial', models.JSONField(help_text='Encodage numérique du visage pour la reconnaissance', verbose_name='Encodage facial')),
                ('image_reference', models.ImageField(upload_to='surveillance/references/', verbose_name='Image de référence')),
                ('qualite_image', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('BONNE', 'Bonne'), ('EXCELLENTE', 'Excellente')], default='MOYENNE', max_length=20, verbose_name="Qualité de l'image")),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('actif', models.BooleanField(default=True, verbose_name='Profil actif')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('detenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_facial', to='detenus.detenu', verbose_name='Détenu')),
            ],
            options={
                'verbose_name': 'Profil facial de détenu',
                'verbose_name_plural': 'Profils faciaux de détenus',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='DetectionFaciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_detection', models.ImageField(upload_to='surveillance/detections/', verbose_name='Image de détection')),
                ('confiance', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de confiance (%)')),
                ('coordonnees_visage', models.JSONField(help_text='Coordonnées du rectangle englobant le visage [x, y, largeur, hauteur]', verbose_name='Coordonnées du visage')),
                ('timestamp', models.DateTimeField(verbose_name='Date et heure de détection')),
                ('est_alerte', models.BooleanField(default=False, verbose_name='Alerte générée')),
                ('motif_alerte', models.TextField(blank=True, null=True, verbose_name="Motif de l'alerte")),
                ('traitee', models.BooleanField(default=False, verbose_name='Détection traitée')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.camera', verbose_name='Caméra')),
                ('detenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detenus.detenu', verbose_name='Détenu identifié')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance.zonesurveillance', verbose_name='Zone de détection')),
            ],
            options={
                'verbose_name': 'Détection faciale',
                'verbose_name_plural': 'Détections faciales',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlerteSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'alerte")),
                ('type_alerte', models.CharField(choices=[('DETECTION_INCONNUE', 'Détection visage inconnu'), ('DETENU_INTERDIT', 'Détenu dans zone interdite'), ('DETECTION_MULTIPLE', 'Détections multiples suspectes'), ('ABSENCE_DETENU', 'Absence de détenu attendu'), ('MOUVEMENT_SUSPECT', 'Mouvement suspect'), ('CAMERA_HORS_SERVICE', 'Caméra hors service'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'alerte")),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('ATTENTION', 'Attention'), ('WARNING', 'Avertissement'), ('CRITIQUE', 'Critique')], default='ATTENTION', max_length=20, verbose_name="Niveau d'alerte")),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('FAUSSE_ALERTE', 'Fausse alerte')], default='OUVERTE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveillance.camera', verbose_name='Caméra concernée')),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveillance.detectionfaciale', verbose_name='Détection concernée')),
                ('detenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detenus.detenu', verbose_name='Détenu concerné')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Alerte de surveillance',
                'verbose_name_plural': 'Alertes de surveillance',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('DETECTION', 'Détection faciale'), ('ALERTE', 'Alerte générée'), ('CAMERA_ON', 'Caméra mise en marche'), ('CAMERA_OFF', 'Caméra arrêtée'), ('MAINTENANCE', 'Maintenance caméra'), ('CONFIG_CHANGE', 'Changement configuration'), ('SYSTEM_START', 'Démarrage système'), ('SYSTEM_STOP', 'Arrêt système')], max_length=30, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('donnees_supplementaires', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP source')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveillance.alertesurveillance', verbose_name='Alerte concernée')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveillance.camera', verbose_name='Caméra concernée')),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveillance.detectionfaciale', verbose_name='Détection concernée')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Historique de surveillance',
                'verbose_name_plural': 'Historiques de surveillance',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['type_evenement', 'timestamp'], name='surveillanc_type_ev_2350b3_idx'), models.Index(fields=['camera', 'timestamp'], name='surveillanc_camera__35725d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='detectionfaciale',
            index=models.Index(fields=['camera', 'timestamp'], name='surveillanc_camera__de7462_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionfaciale',
            index=models.Index(fields=['detenu', 'timestamp'], name='surveillanc_detenu__61bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionfaciale',
            index=models.Index(fields=['est_alerte', 'traitee'], name='surveillanc_est_ale_7f7356_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('centre', 'code')},
        ),
        migrations.AddIndex(
            model_name='alertesurveillance',
            index=models.Index(fields=['statut', 'date_creation'], name='surveillanc_statut_547728_idx'),
        ),
        migrations.AddIndex(
            model_name='alertesurveillance',
            index=models.Index(fields=['niveau', 'date_creation'], name='surveillanc_niveau_f959fb_idx'),
        ),
    ]
