# Generated by Django 4.2.7 on 2025-09-27 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Congolaise', max_length=100, verbose_name='Nationalité')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_arrestation', models.DateField(verbose_name="Date d'arrestation")),
                ('date_incarceration', models.DateField(verbose_name="Date d'incarcération")),
                ('motif_incarceration', models.TextField(verbose_name="Motif d'incarcération")),
                ('tribunal', models.CharField(max_length=200, verbose_name='Tribunal')),
                ('numero_dossier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de dossier')),
                ('avocat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Avocat')),
                ('telephone_avocat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone avocat')),
                ('cellule', models.CharField(max_length=20, verbose_name='Cellule')),
                ('regime', models.CharField(choices=[('PREVENTIF', 'Préventif'), ('CONDAMNE', 'Condamné'), ('AMENDE', 'Amende'), ('TRAVAUX_INTERET', "Travaux d'intérêt général")], default='PREVENTIF', max_length=20, verbose_name='Régime')),
                ('statut', models.CharField(choices=[('INCARCERE', 'Incarcéré'), ('LIBERE', 'Libéré'), ('TRANSFERE', 'Transféré'), ('EVADE', 'Évadé'), ('DECEDE', 'Décédé')], default='INCARCERE', max_length=20, verbose_name='Statut')),
                ('duree_peine_mois', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1200)], verbose_name='Durée de peine (mois)')),
                ('date_liberation_prevue', models.DateField(blank=True, null=True, verbose_name='Date de libération prévue')),
                ('date_liberation_effective', models.DateField(blank=True, null=True, verbose_name='Date de libération effective')),
                ('motif_liberation', models.TextField(blank=True, null=True, verbose_name='Motif de libération')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('maladies_chroniques', models.TextField(blank=True, null=True, verbose_name='Maladies chroniques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detenus_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Détenu',
                'verbose_name_plural': 'Détenus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDetenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('ancienne_valeur', models.TextField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='detenus.detenu', verbose_name='Détenu')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique détenu',
                'verbose_name_plural': 'Historiques détenus',
                'ordering': ['-created_at'],
            },
        ),
    ]
