# Generated by Django 4.2.7 on 2025-09-27 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detenus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detenu',
            name='adn',
            field=models.TextField(blank=True, help_text='Profil ADN du détenu (encodé)', null=True, verbose_name='Profil ADN'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='cicatrices',
            field=models.TextField(blank=True, help_text='Description des cicatrices, tatouages, piercings, etc.', null=True, verbose_name='Cicatrices et marques distinctives'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='couleur_cheveux',
            field=models.CharField(blank=True, choices=[('NOIR', 'Noir'), ('BRUN', 'Brun'), ('BLOND', 'Blond'), ('ROUX', 'Roux'), ('BLANC', 'Blanc'), ('CHATAIN', 'Châtain')], max_length=20, null=True, verbose_name='Couleur des cheveux'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='couleur_peau',
            field=models.CharField(blank=True, choices=[('CLAIR', 'Clair'), ('MAT', 'Mat'), ('BRUN', 'Brun'), ('NOIR', 'Noir'), ('MIXTE', 'Mixte')], max_length=20, null=True, verbose_name='Couleur de peau'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='couleur_yeux',
            field=models.CharField(blank=True, choices=[('NOIR', 'Noir'), ('MARRON', 'Marron'), ('BLEU', 'Bleu'), ('VERT', 'Vert'), ('GRIS', 'Gris'), ('NOISETTE', 'Noisette')], max_length=20, null=True, verbose_name='Couleur des yeux'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='empreintes_digitales',
            field=models.TextField(blank=True, help_text='Données des empreintes digitales (encodées)', null=True, verbose_name='Empreintes digitales'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='photo_face',
            field=models.ImageField(blank=True, help_text='Photo de face du détenu', null=True, upload_to='detenus/photos/', verbose_name='Photo de face'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil du détenu', null=True, upload_to='detenus/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kilogrammes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='taille',
            field=models.PositiveIntegerField(blank=True, help_text='Taille en centimètres', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='detenu',
            name='type_cheveux',
            field=models.CharField(blank=True, choices=[('LISSE', 'Lisse'), ('ONDULE', 'Ondulé'), ('BOUCLE', 'Bouclé'), ('CREPU', 'Crépu'), ('RAIDE', 'Raide')], max_length=20, null=True, verbose_name='Type de cheveux'),
        ),
    ]
