# Generated by Django 4.2.7 on 2026-01-22 18:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detenus', '0002_detenu_adn_detenu_cicatrices_detenu_couleur_cheveux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentrePenitencier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du centre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du centre')),
                ('type_centre', models.CharField(choices=[('PRISON', 'Prison'), ('MAISON_D_ARRET', "Maison d'arrêt"), ('CENTRE_DE_DETENTION', 'Centre de détention'), ('ETABLISSEMENT_PENITENTIAIRE', 'Établissement pénitentiaire')], default='PRISON', max_length=30, verbose_name='Type de centre')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité maximale')),
                ('capacite_actuelle', models.PositiveIntegerField(default=0, verbose_name='Capacité actuelle')),
                ('directeur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Directeur')),
                ('date_ouverture', models.DateField(verbose_name="Date d'ouverture")),
                ('statut', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Centre pénitencier',
                'verbose_name_plural': 'Centres pénitenciers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AdminPrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_admin', models.CharField(max_length=20, unique=True, verbose_name='Matricule administrateur')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('date_affectation', models.DateField(verbose_name="Date d'affectation")),
                ('statut', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detenus.centrepenitencier', verbose_name='Centre pénitencier')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Administrateur de prison',
                'verbose_name_plural': 'Administrateurs de prison',
                'ordering': ['centre__nom', 'utilisateur__first_name'],
            },
        ),
        migrations.AddField(
            model_name='detenu',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='detenus.centrepenitencier', verbose_name='Centre pénitencier'),
        ),
    ]
