# Generated by Django 4.2.7 on 2026-02-20 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detenus', '0003_centrepenitencier_adminprison_detenu_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDetenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.CharField(max_length=20, unique=True, verbose_name='Numéro de fiche')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20, verbose_name='Statut de validation')),
                ('informations_supplementaires', models.JSONField(blank=True, default=dict, verbose_name='Informations supplémentaires')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detenus.detenu', verbose_name='Détenu')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Fiche détenu',
                'verbose_name_plural': 'Fiches détenus',
                'ordering': ['-date_emission'],
            },
        ),
    ]
