# Generated by Django 4.2.7 on 2026-09-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detenus', '0005_detenu_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavillon', models.CharField(max_length=20, verbose_name='Pavillon')),
                ('nom_pavillon', models.CharField(max_length=100, verbose_name='Nom du pavillon')),
                ('code', models.CharField(max_length=20, verbose_name='Code cellule')),
                ('type_population', models.CharField(choices=[('HOMMES', 'Hommes'), ('FEMMES', 'Femmes')], default='HOMMES', max_length=10, verbose_name='Population')),
                ('capacite', models.PositiveIntegerField(default=4, verbose_name='Capacité')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellules', to='detenus.centrepenitencier', verbose_name='Centre')),
            ],
            options={
                'verbose_name': 'Cellule',
                'verbose_name_plural': 'Cellules',
                'ordering': ['centre', 'pavillon', 'code'],
                'unique_together': {('centre', 'code')},
            },
        ),
    ]
