# Generated by Django 4.2.7 on 2025-09-27 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('date_livraison_effective', models.DateField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact principal')),
                ('specialite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Spécialité')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_produit', models.CharField(choices=[('NOURRITURE', 'Nourriture'), ('MEDICAMENT', 'Médicament'), ('VETEMENT', 'Vêtement'), ('LINGE', 'Linge'), ('MATERIEL_ENTRETIEN', "Matériel d'entretien"), ('MATERIEL_BUREAU', 'Matériel de bureau'), ('SECURITE', 'Sécurité'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de produit')),
                ('unite_mesure', models.CharField(choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('ML', 'Millilitre'), ('UNITE', 'Unité'), ('PAQUET', 'Paquet'), ('CARTON', 'Carton'), ('M', 'Mètre'), ('M2', 'Mètre carré')], max_length=10, verbose_name='Unité de mesure')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.PositiveIntegerField(default=10, verbose_name='Stock minimum')),
                ('stock_maximum', models.PositiveIntegerField(default=1000, verbose_name='Stock maximum')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('fournisseur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='logistique.fournisseur', verbose_name='Fournisseur principal')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('PERTE', 'Perte')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='logistique.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField(verbose_name='Quantité commandée')),
                ('quantite_livree', models.PositiveIntegerField(default=0, verbose_name='Quantité livrée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant de la ligne')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='logistique.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='logistique.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['produit__nom'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='logistique.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
