# Generated by Django 4.2.7 on 2025-09-27 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detenus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('type_visiteur', models.CharField(choices=[('FAMILLE', 'Famille'), ('AVOCAT', 'Avocat'), ('AMI', 'Ami'), ('REPRESENTANT_LEGAL', 'Représentant légal'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de visiteur')),
                ('piece_identite', models.CharField(max_length=50, verbose_name="Pièce d'identité")),
                ('numero_piece', models.CharField(max_length=50, verbose_name='Numéro de pièce')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('relation_detenu', models.CharField(max_length=100, verbose_name='Relation avec le détenu')),
                ('cabinet_avocat', models.CharField(blank=True, max_length=200, null=True, verbose_name="Cabinet d'avocat")),
                ('numero_ordre_avocat', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'ordre avocat")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(verbose_name='Date de visite')),
                ('duree_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)], verbose_name='Durée en minutes')),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée'), ('REFUSEE', 'Refusée')], default='PROGRAMMEE', max_length=20, verbose_name='Statut')),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name='Motif de refus')),
                ('objets_apportes', models.TextField(blank=True, null=True, verbose_name='Objets apportés')),
                ('objets_autorises', models.TextField(blank=True, null=True, verbose_name='Objets autorisés')),
                ('objets_refuses', models.TextField(blank=True, null=True, verbose_name='Objets refusés')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('agent_controle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_controlees', to=settings.AUTH_USER_MODEL, verbose_name='Agent de contrôle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='detenus.detenu', verbose_name='Détenu')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='visites.visiteur', verbose_name='Visiteur')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='ObjetVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_objet', models.CharField(max_length=200, verbose_name="Nom de l'objet")),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('autorise', models.BooleanField(default=False, verbose_name='Autorisé')),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name='Motif de refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets', to='visites.visite', verbose_name='Visite')),
            ],
            options={
                'verbose_name': 'Objet visite',
                'verbose_name_plural': 'Objets visite',
                'ordering': ['nom_objet'],
            },
        ),
    ]
