# Generated by Django 4.2.7 on 2025-09-27 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detenus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_consultation', models.CharField(choices=[('CONSULTATION_GENERALE', 'Consultation générale'), ('URGENCE', 'Urgence'), ('SUIVI_MEDICAL', 'Suivi médical'), ('VACCINATION', 'Vaccination'), ('EXAMEN_LABORATOIRE', 'Examen de laboratoire'), ('CONSULTATION_PSYCHOLOGIQUE', 'Consultation psychologique')], max_length=30, verbose_name='Type de consultation')),
                ('date_consultation', models.DateTimeField(verbose_name='Date de consultation')),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PROGRAMMEE', max_length=20, verbose_name='Statut')),
                ('symptomes', models.TextField(verbose_name='Symptômes')),
                ('diagnostic', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('traitement_prescrit', models.TextField(blank=True, null=True, verbose_name='Traitement prescrit')),
                ('recommandations', models.TextField(blank=True, null=True, verbose_name='Recommandations')),
                ('date_controle', models.DateTimeField(blank=True, null=True, verbose_name='Date de contrôle')),
                ('urgence', models.BooleanField(default=False, verbose_name='Urgence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='detenus.detenu', verbose_name='Détenu')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_medicales', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('nom_commercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom commercial')),
                ('type_medicament', models.CharField(choices=[('ANTIBIOTIQUE', 'Antibiotique'), ('ANALGESIQUE', 'Analgésique'), ('ANTI_INFLAMMATOIRE', 'Anti-inflammatoire'), ('VITAMINE', 'Vitamine'), ('CHRONIQUE', 'Médicament chronique'), ('URGENCE', "Médicament d'urgence")], max_length=30, verbose_name='Type de médicament')),
                ('forme_pharmaceutique', models.CharField(max_length=100, verbose_name='Forme pharmaceutique')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.PositiveIntegerField(default=10, verbose_name='Stock minimum')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=200, verbose_name='Nom du vaccin')),
                ('date_vaccination', models.DateField(verbose_name='Date de vaccination')),
                ('lot_vaccin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lot du vaccin')),
                ('effets_secondaires', models.TextField(blank=True, null=True, verbose_name='Effets secondaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='detenus.detenu', verbose_name='Détenu')),
                ('medecin_vaccinateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Médecin vaccinateur')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-date_vaccination'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(max_length=200, verbose_name='Posologie')),
                ('duree_jours', models.PositiveIntegerField(verbose_name='Durée en jours')),
                ('quantite_prescrit', models.PositiveIntegerField(verbose_name='Quantité prescrite')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='soins.consultation', verbose_name='Consultation')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='soins.medicament', verbose_name='Médicament')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_antecedent', models.CharField(max_length=100, verbose_name="Type d'antécédent")),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('traitement_suivi', models.TextField(blank=True, null=True, verbose_name='Traitement suivi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='detenus.detenu', verbose_name='Détenu')),
            ],
            options={
                'verbose_name': 'Antécédent médical',
                'verbose_name_plural': 'Antécédents médicaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
